const DOM = {
  contactsListEl: document.getElementById("contacts-list"),
  dialogEl: document.getElementById("dialog"),
  headlineEl: document.getElementById("dialog-headline"),
  noButtonEl: document.getElementById("no-button"),
  okButtonEl: document.getElementById("ok-button"),
  contactOverviewContainerEl: document.getElementById(
    "contact-overview-container",
  ),
  contactOverviewEl: document.getElementById("contact-overview"),
  contactNameEl: document.getElementById("contact-name-input"),
  contactEmailEl: document.getElementById("contact-email-input"),
  contactPhoneEl: document.getElementById("contact-phone-input"),
  closeButtonEl: document.getElementById("close-button"),
  personImageEl: document.getElementById("person-image"),
  warningMessageNameEl: document.getElementById("warning-name"),
  warningMessageEmailEl: document.getElementById("warning-email"),
  warningMessagePhoneEl: document.getElementById("warning-phone"),
  userButtonEl: document.getElementById("profile-button"),
  screenDesktopEl: document.getElementById("screen-desktop"),
  fullscreenMobileEl: document.getElementById("fullscreen-mobile"),
  mobileContactMenuButtonEl: document.getElementById(
    "mobile-contact-menu-button",
  ),
  mobileMenuEl: document.getElementById("mobile-menu"),
  toastMessageEl: document.getElementById("toast-message"),
  toastSectionEl: document.getElementById("toast-section"),
};
